pages:
  stage: deploy
  script:
    - mkdir $CI_PROJECT_DIR\public
    #    - cp -r ./* .public
    - Copy-Item -Path (Get-Item -Path "$CI_PROJECT_DIR\*" -Exclude ('$CI_PROJECT_DIR\.public','$CI_PROJECT_DIR\.git')).FullName -Destination $CI_PROJECT_DIR\.public -Recurse -Force
    - Get-ChildItem $CI_PROJECT_DIR\* -Include $CI_PROJECT_DIR\public -Recurse | Remove-Item -Recurse
    - Rename-Item -Path $CI_PROJECT_DIR\.public $CI_PROJECT_DIR\public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "gh-pages"