pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r ./* .public
    - Get-ChildItem * -Include /public -Recurse | Remove-Item
    - Rename-Item -Path .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH