site_name: UNIQVUE MANUAL
pages:
  - Übersicht: index.md
  - Manager:
    - Session Manager: sessionmanager.md
    - Login: login.md
    - Dashboard: dashboard.md
    - Bedienelemente: bedienelemente.md
    - Sessions: sessions.md
    - Toolboxes: toolbox.md
    - Team Gallery: teamgallery.md
    - Styles: styles.md
      #    - Module: module.md
    
    - Module:
      - Übersicht: modulesoverview.md
      - Singleview Module:
        - Title: Module_Manager/title.md
        - Bullet List: Module_Manager/bulletlist.md
        - Browser: Module_Manager/browser.md
        - HTML: Module_Manager/html.md
        - Pause: Module_Manager/pause.md
        - Video Player: Module_Manager/videoplayer.md
        - Share Price: Module_Manager/shareprice.md
        - Slideshow: Module_Manager/slideshow.md
        - External Source: Module_Manager/externalsource.md
      - Multiview Module:
        - Storyboard: Module_Manager/storyboard.md
        - Input Selector: Module_Manager/inputselector.md
        - Challenges: Module_Manager/challenges.md
        
    - Asset Browser: assetbrowser.md
    - Session Workflow: sessionworkflow.md
    - Toolbox Workflow: toolboxworkflow.md
    - Style Workflow: styleworkflow.md
  - Showroom:
    - Showroom Übersicht: showroom.md
    - Home Screen: homescreen.md
    #- Agenda: agenda.md
    - Agenda: agendaalternate.md
    - Disc: disc.md

plugins:
  - search
markdown_extensions:
  - attr_list
theme:
  name: material
  features:
    - navigation.top
    - toc.integrate
    - search.suggest
  palette:
    - primary: black
  logo: img/logo.png
  favicon: img/logo.png

extra:
  version:
    provider: mike
