site_name: UNIQVUE MANUAL
nav:
  - Übersicht:                  index.md
  - Manager:
    - UNIQVUE Manager:          002_sessionmanager.md
    - Login:                    003_login.md
    - Dashboard:                004_dashboard.md
    - Bedienelemente:           005_bedienelemente.md
    - Shows:                    00100_shows.md
 
    - Sessions:                 006_sessions.md
      #- Session Editor:         00102_sessioneditor.md
      #- Session Workflow:       051_sessionworkflow.md
    - Toolboxes:                007_toolbox.md
      #- Toolbox List:           
      #- Toolbox Editor:         00103_toolboxeditor.md
      #- Toolbox Workflow:       052_toolboxworkflow.md
    
    - Styles:                   009_styles.md
      #- Style Editor:           00104_styleditor.md
      #- Style Workflow:         053_styleworkflow.md
      #    - Module: module.md
    
    - Module:
      - Übersicht:              011_modulesoverview.md
      - Singleview Module:
        - Title:                012_title.md
        - Bullet List:          013_bulletlist.md
        - Browser:              014_browser.md
        - HTML:                 015_html.md
        - Pause:                016_pause.md
        - Video Player:         017_videoplayer.md
        - Share Price:          018_shareprice.md
        - Slideshow+:           019_slideshowplus.md
        - Bar Chart:            020_barchart.md
        - External Source:      021_externalsource.md
    
      - Multiview Module:
        - Storyboard+:          022_storyboardplus.md
    #    - Input Selector:       023_inputselector.md
        - Challenges:           024_challenges.md
        - Timeline:             025_timeline.md

      # - System Tools:           
      #   - Frame Manager:        022_storyboardplus.md
      #   - Confidential:         022_storyboardplus.md
      #   - Snap Shot:            022_storyboardplus.md
      #   - Paint:                022_storyboardplus.md
      #   - Microphone:           022_storyboardplus.md
        
    - Asset Browser:            050_assetbrowser.md
    - Administration:           010_administration.md
    #- Show Workflow:            00101_showworkflow.md
    #- Session Workflow:         051_sessionworkflow.md
    #- Toolbox Workflow:         052_toolboxworkflow.md
    #- Style Workflow:           053_styleworkflow.md
  - Showroom:
    - Showroom Übersicht:       054_showroom.md
    - Home Screen:              055_homescreen.md
    - Agenda & Module:          056_agenda.md
    - Disc:                     057_disc.md
  - Technische Spezifikation:
    - Netzwerk und Hardware:    058_tecspec.md

plugins:
  - search
    # - pdf-export
markdown_extensions:
  - attr_list
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  features:
    - navigation.top
    - toc.integrate
    - search.suggest
  palette:
    - primary: black
    - accent: teal
  logo: img/logo.png
  favicon: img/logo.png

use_directory_urls: false
extra:
  version:
    provider: mike
    default: latest
extra_css:
  - font.css
