site_name: UNIQVUE MANUAL
nav:
  - Übersicht:                  index.md
  - Manager:
    - UNIQVUE Manager:          002_uniqvuemanager.md
    - Login:                    003_login.md
    - Home:                004_dashboard.md
    - Navigation und Tools:           005_bedienelemente.md
    - Shows:                    00100_shows.md
    - Sessions:                 006_sessions.md
    - Toolboxes:                007_toolbox.md
    - Styles:                   009_styles.md
    - Module:
      - Übersicht:              011_modulesoverview.md
      - Singleview Module:
        - Title:                012_title.md
        - Bullet List:          013_bulletlist.md
        - Browser:              014_browser.md
        - HTML:                 015_html.md
        - Pause:                016_pause.md
        - Video Player:         017_videoplayer.md
        - Share Price:          018_shareprice.md
        - Slideshow+:           019_slideshowplus.md
        - Bar Chart:            020_barchart.md
        - External Source:      021_externalsource.md
        - Icon Array:           026_iconarray.md
    
      - Multiview Module:
        - Storyboard+:          022_storyboardplus.md
      # - Input Selector:       023_inputselector.md
        - Challenges:           024_challenges.md
        - Timeline:             025_timeline.md
        
    - Asset Browser:            050_assetbrowser.md
    - Administration:           010_administration.md
    
  - Showroom:
    - Showroom Übersicht:       054_showroom.md
    - Home Screen:              055_homescreen.md
    - Agenda & Module:          056_agenda.md
    - Disc:                     057_disc.md
  - Uniqvue Remote:             
    - Installation:             00101_uniqvueremote.md
    - User Interface:           00102_remoteuserinterface.md                       
  - Technische Spezifikation:
    - Netzwerk und Hardware:    058_tecspec.md

plugins:
  - search
    # - pdf-export
markdown_extensions:
  - attr_list
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  features:
    - navigation.top
    - toc.integrate
    - search.suggest
  palette:
    - primary: black
    - accent: teal
  logo: img/logo.png
  favicon: img/logo.png

use_directory_urls: false
extra:
  version:
    provider: mike
    default: latest
extra_css:
  - font.css
