site_name: UNIQVUE MANUAL
pages:
  - Übersicht:                  index.md
  - Manager:
    - Session Manager:          002_sessionmanager.md
    - Login:                    003_login.md
    - Dashboard:                004_dashboard.md
    - Bedienelemente:           005_bedienelemente.md
    - Sessions:                 006_sessions.md
    - Toolboxes:                007_toolbox.md
    - Team Gallery:             008_teamgallery.md
    - Styles:                   009_styles.md
    - Administration:           010_administration.md
      #    - Module: module.md
    
    - Module:
      - Übersicht:              011_modulesoverview.md
      - Singleview Module:
        - Title:                012_title.md
        - Bullet List:          013_bulletlist.md
        - Browser:              014_browser.md
        - HTML:                 015_html.md
        - Pause:                016_pause.md
        - Video Player:         017_videoplayer.md
        - Share Price:          018_shareprice.md
        - Slideshow+:           019_slideshowplus.md
        - Bar Chart:            020_barchart.md
        - External Source:      021_externalsource.md
    
      - Multiview Module:
        - Storyboard+:          022_storyboardplus.md
        - Input Selector:       023_inputselector.md
        - Challenges:           024_challenges.md
        - Timeline:             025_timeline.md
        
    - Asset Browser:            050_assetbrowser.md
    - Session Workflow:         051_sessionworkflow.md
    - Toolbox Workflow:         052_toolboxworkflow.md
    - Style Workflow:           053_styleworkflow.md
  - Showroom:
    - Showroom Übersicht:       054_showroom.md
    - Home Screen:              055_homescreen.md
    - Agenda:                   056_agenda.md
    - Disc:                     057_disc.md
  - Technische Spezifikation:
    - Netzwerk und Hardware:    058_tecspec.md

plugins:
  - search
    # - pdf-export
markdown_extensions:
  - attr_list
theme:
  name: material
  features:
    - navigation.top
    - toc.integrate
    - search.suggest
  palette:
    - primary: black
    - accent: teal
  logo: img/logo.png
  favicon: img/logo.png
use_directory_urls: false
extra:
  version:
    provider: mike
    default: latest
